package com.bayport.dto;

import java.time.LocalDate;

public record VaccinationScheduleItem(
        String vaccineName,
        LocalDate lastGiven,
        LocalDate nextDue,
        String status,
        String source,
        boolean autoGenerated
) {}
